apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: mavenflow
data:
  PORT: "3001"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "mavenflow"
  DB_USER: "mavenflow"
  # Ajuste para o domínio do frontend em produção
  CORS_ORIGIN: "https://mavenflow.seudominio.internal"
