apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mavenflow
type: Opaque
stringData:
  POSTGRES_DB: mavenflow
  POSTGRES_USER: mavenflow
  # ALTERE esta senha antes de aplicar em produção
  POSTGRES_PASSWORD: "change_me_in_production"
